Ram forms followup
greymass/2nicove pull request #85
Opened 2024-08-29 20:05 UTC by dafuga

2024-08-30 15:47 UTC, aaroncox approved these changes

2024-08-30 15:47 UTC, aaroncox commented on src/lib/components/input/assetOrUnits.svelte
> +<script lang="ts">
I'm not sure this component makes any sense. Why wouldn't the form itself just change what input its using?

2024-08-30 16:01 UTC, aaroncox requested changes

2024-08-30 16:01 UTC, aaroncox commented on src/routes/[network]/(account)/ram/buy/state.svelte.ts
> +		this.tokens = Asset.fromUnits(0, this.chain?.systemToken?.symbol || '4,EOS');
The value of `this.chain` shouldn't be optional and you shouldn't ever need to default to `4,EOS`. 

If you do, we gotta change something somewhere else. I don't want to scatter the `4,EOS` symbol all over the app.

2024-08-31 05:06 UTC, dafuga commented on src/lib/components/input/assetOrUnits.svelte
> +<script lang="ts">
I thought we talked about making this component 😅 IMO having a component like this makes sense if we feel like the asset/units pair of inputs is one that we are going to use in a few places. If you don't think so then I agree that we don't need this component.

2024-08-31 05:13 UTC, dafuga commented on src/routes/[network]/(account)/ram/buy/+page.svelte
> +		const actionName = buyRamState.format === 'asset' ? 'buyram' : 'buyrambytes';
Maybe? 🤔 I feel like it's a bit overkill, but if you think that it would be valuable to be able to link to a specific method then I'm not against the idea.

2024-08-31 05:22 UTC, dafuga commented on src/routes/[network]/(account)/ram/buy/state.svelte.ts
> +		this.tokens = Asset.fromUnits(0, this.chain?.systemToken?.symbol || '4,EOS');
it looks like systemToken is optional right now 🤔

2024-08-31 07:26 UTC, aaroncox commented on src/lib/components/input/assetOrUnits.svelte
> +<script lang="ts">
I mentioned needing a component for integers, but didn't remember mentioning a component that does both an asset and an integer. The only place I can imagine this being used is on the buy/sell pages for RAM 🤔

2024-08-31 07:26 UTC, aaroncox commented on src/routes/[network]/(account)/ram/+page.svelte
> +			const response = await fetch('https://unicove-eos.greymass.io/api/marketprice/ram');
The base URL should also be a environmental variable and not hardcoded. 

Maybe a `API_EOS_METRICS` and `JUNGLE4_API_METRICS` to mirror the others.

2024-08-31 07:26 UTC, aaroncox commented on src/routes/[network]/(account)/ram/buy/+page.svelte
> +		const actionName = buyRamState.format === 'asset' ? 'buyram' : 'buyrambytes';
Maybe it is, I'm not entirely sure. I imagined this from the start as being multiple pages with maybe some shared components between them. But now that we're faced with the decision I'm not entirely sure which is best. That's why I figured I'd at least bring it up.

2024-08-31 07:28 UTC, aaroncox commented on src/routes/[network]/(account)/ram/buy/state.svelte.ts
> +		this.tokens = Asset.fromUnits(0, this.chain?.systemToken?.symbol || '4,EOS');
Hrm it is, but we should require it. If its not set something's wrong (despite what the type says).

2024-08-31 19:36 UTC, dafuga commented on src/lib/components/input/assetOrUnits.svelte
> +<script lang="ts">
Maybe we misunderstood each other 😅 I'm actually also having a hard time coming up with other use cases for it 🤔 The only I can think of off the top of my head is that it could be used to buy and sell something like drops.

2024-09-02 17:11 UTC, aaroncox commented on yarn.lock
> +
Maybe discard this change to avoid a conflict?

2024-09-03 17:03 UTC, aaroncox commented on src/lib/components/input/asset.svelte
> -	import TextInput from './textinput.svelte';
I'm not sure if this was named `textinput` for a specific reason. It might have been to avoid conflicts/confusion with other generic `Text` imports. @deansallinen any insights?

2024-09-03 17:03 UTC, aaroncox commented on src/lib/components/input/assetOrUnits.svelte
> +<script lang="ts">
I'm not sure it'd be used there either, since drops are generated/destroyed and you don't ever enter the amount of EOS/RAM.

2024-09-03 17:03 UTC, aaroncox commented on src/lib/components/input/assetOrUnits.svelte
> +	import { createEventDispatcher, type ComponentProps } from 'svelte';
Is this ever used?

2024-09-03 17:03 UTC, aaroncox commented on src/lib/components/input/text.svelte
> +	const dispatch = createEventDispatcher();
Is this ever used?

2024-09-03 17:20 UTC, dafuga commented on src/lib/components/input/assetOrUnits.svelte
> +<script lang="ts">
But you could decide to generate drops based on either a unit number or EOS amount in which case you could use that component.

2024-09-03 17:21 UTC, dafuga commented on src/lib/components/input/assetOrUnits.svelte
> +	import { createEventDispatcher, type ComponentProps } from 'svelte';
No 😄 That's why I hadn't marked the PR as ready for review yet, I still need to do some cleanup.

2024-09-03 20:21 UTC, deansallinen commented on src/lib/components/input/asset.svelte
> -	import TextInput from './textinput.svelte';
I think it was a holdover from when it wasn't in the `/input` directory. I don't know if just `<Text>` would make sense when reading the markup since it's an input... but the filename can change - that's fine. I'd also like to move to using an 'index.ts' file in each folder so we keep consistent import names in our pages. e.g. `import {TextInput, Asset} from '$components/input'`

2024-09-03 21:11 UTC, aaroncox commented on src/lib/components/input/assetOrUnits.svelte
> +<script lang="ts">
You'd never input an EOS amount for Droplets I don't think.

2024-09-03 21:11 UTC, aaroncox commented on src/lib/components/input/asset.svelte
> -	import TextInput from './textinput.svelte';
I was mostly worried that a `<Text />` element would conflict with something else. I suppose we could just import it as `InputText` or `TextInput` still though.

2024-09-03 21:11 UTC, aaroncox commented on src/lib/wharf/chains.ts
> +import { PUBLIC_API_EOS_METRICS } from '$env/static/public';
This should be private and named `API_EOS_METRICS`.

We don't want this endpoint to be publicly known.

2024-09-03 21:11 UTC, aaroncox commented on src/lib/wharf/chains.ts
> +		url: string;
This isn't a `ramPrices` attribute. This API endpoint provides a ton of other metrics, which is why the configuration parameter is called `timeseries`. This should be renamed to reflect that, and probably just be a root property called something like `timeseries_api` or something.

2024-09-03 21:11 UTC, aaroncox commented on src/routes/[network]/(account)/ram/+page.svelte
> +			const response = await fetch('https://unicove-eos.greymass.io/api/marketprice/ram');
Like I mentioned in the other comment, this needs to be pulled out and placed inside of a `+page.server.ts` file.

2024-09-03 21:11 UTC, aaroncox commented on src/routes/[network]/(account)/ram/+page.svelte
> +					value: Asset.from(price.value / 10000, data.network.chain.systemToken?.symbol || '4,EOS')
We talked about removing this and I didn't have a solution at the time - but before this call, just throw an error if the system token isn't defined. We do not want to default to EOS.

2024-09-03 21:11 UTC, aaroncox commented on src/routes/[network]/(account)/ram/buy/bytes/+page.svelte
> +			transactionId = transactionResult?.resolved?.transaction.id;
If we don't get a transaction ID, should this proceed? 

Instead of these optional variables, should we throw an error here if the result or resolved transaction isn't set?

2024-09-03 21:11 UTC, aaroncox commented on src/lib/components/transaction.svelte
> +	<h3 class="h3">{transaction?.status}</h3>
If the transaction isn't found, should it be showing transaction complete?

2024-09-03 21:11 UTC, aaroncox commented on src/routes/[network]/(account)/ram/buy/bytes/+page.svelte
> +				buyRamState.balance = context.account.balance?.liquid;
If this value isn't set, won't this break the form?

2024-09-03 21:14 UTC, aaroncox commented
The Jungle 4 version just sits saying "loading ram prices" - but that feature doesn't exist on Jungle and will never load.

2024-09-03 21:15 UTC, aaroncox commented on src/routes/[network]/(account)/ram/buy/bytes/+page.svelte
> +			disabled={!context.account}
I wouldn't disable this if there's no account. It might be useful for someone on the form, who's not logged in, to see how much a specific amount would cost by typing it in?

2024-09-04 02:02 UTC, dafuga commented on src/lib/components/input/asset.svelte
> -	import TextInput from './textinput.svelte';
Yeah exactly.

2024-09-04 02:05 UTC, dafuga commented on src/lib/components/input/assetOrUnits.svelte
> +<script lang="ts">
I can see some users wanting to buy droplets based on an amount of EOS (for the same reason that some people like to buy a specific EOS amount of RAM).

2024-09-04 02:08 UTC, dafuga commented on src/lib/wharf/chains.ts
> +import { PUBLIC_API_EOS_METRICS } from '$env/static/public';
Why do we not want it to be known? If I make it private then I won't be able to use the variable here. I guess we could make an `/api/[network]/ramprices` server-side endpoint for this though.

2024-09-04 02:13 UTC, dafuga commented on src/routes/[network]/(account)/ram/buy/bytes/+page.svelte
> +				buyRamState.balance = context.account.balance?.liquid;
What do you mean by breaking the form? The balance defaults to 0 so you'll get a validation error if you try to input any amount.

2024-09-04 02:14 UTC, dafuga commented on src/routes/[network]/(account)/ram/buy/bytes/+page.svelte
> +			disabled={!context.account}
Hmm I guess that makes sense.

2024-09-04 15:18 UTC, aaroncox commented on src/lib/wharf/chains.ts
> +import { PUBLIC_API_EOS_METRICS } from '$env/static/public';
Because we don't want people to hit the API directly and abuse it. This needs to be a private API, which only the SSR version of Unicove knows how to access, and essentially proxy/cache it.

2024-09-04 15:20 UTC, aaroncox commented on src/routes/[network]/(account)/ram/buy/bytes/+page.svelte
> +				buyRamState.balance = context.account.balance?.liquid;
Alright cool. I just wanted to make sure if the balance didn't exist, the default balance wouldn't cause the form to break!

2024-09-04 15:26 UTC, aaroncox commented on src/lib/wharf/chains.ts
> +import { PUBLIC_API_EOS_METRICS } from '$env/static/public';
And yes, this should be a server-side endpoint, probably something like:

```
/api/[network]/metrics/marketprice/ram
```

`marketprice` is the name of the data series, and `ram` is the measurement being used.

2024-09-04 18:26 UTC, dafuga commented on src/lib/wharf/chains.ts
> +import { PUBLIC_API_EOS_METRICS } from '$env/static/public';
People will be able to abuse the `/api/[network]/metrics/marketprice/ram` though 🤔

2024-09-04 18:28 UTC, dafuga commented on src/lib/wharf/chains.ts
> +import { PUBLIC_API_EOS_METRICS } from '$env/static/public';
But yeah, adding caching through cloudflare is probably going to be easier so that's already a good reason to do it this way 👍

2024-09-04 19:15 UTC, dafuga commented on src/routes/[network]/(account)/ram/buy/bytes/+page.svelte
> +			transactionId = transactionResult?.resolved?.transaction.id;
That's already happening in the `transact` method. I do need the optionals though because that method is returning a `TransactResult` object and that type marks `resolved` as optional.

2024-09-04 19:58 UTC, dafuga commented on src/lib/components/input/assetOrUnits.svelte
> +<script lang="ts">
I'm also not sure why we're still talking about this 😂 I was just pointing out that if we wanted to have a droplets page at some point, you could use a component like this one to let the user generate a certain amount of droplets (you're right that the user wouldn't be buying the droplets, but we could present it as a purchase if we have him buy the RAM needed before generating the droplets).

2024-09-04 20:03 UTC, dafuga commented on src/routes/[network]/(account)/ram/+page.svelte
> +			const response = await fetch('https://unicove-eos.greymass.io/api/marketprice/ram');
Do we have a Jungle 4 metrics API right now? 🤔

2024-09-04 21:53 UTC, deansallinen commented on src/lib/components/input/asset.svelte
> -	import TextInput from './textinput.svelte';
Yeah `import TextInput from '$lib/components/input/text'` is fine. 

`import {TextInput} from '$lib/components'` is even better

2024-09-05 02:28 UTC, aaroncox approved these changes

2024-09-05 02:56 UTC, dafuga commented on src/lib/wharf/chains.ts
> +import { PUBLIC_API_EOS_METRICS } from '$env/static/public';
Oh interersting, I hadn't realized that cf protected us against abuse in any way 🤔

2024-09-05 02:56 UTC, merged